# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
unordered_multichain_mode: true
preload_handlers: true
rollback_on_reorg: false
contracts:
  - name: AaveProxy
    handler: src/EventHandlers.ts
    events:
      - event: LiquidationCall(address indexed collateralAsset, address indexed debtAsset, address indexed user, uint256 debtToCover, uint256 liquidatedCollateralAmount, address liquidator, bool receiveAToken)
        field_selection:
          transaction_fields:
            - hash
  - name: EulerFactory
    handler: src/EventHandlers.ts
    events:
      - event: ProxyCreated(address indexed proxy, bool upgradeable, address implementation, bytes trailingData)
  - name: EulerVaultProxy
    handler: src/EventHandlers.ts
    events:
      - event: Liquidate(address indexed liquidator, address indexed violator, address collateral, uint256 repayAssets, uint256 yieldBalance)
        field_selection:
          transaction_fields:
            - hash
  - name: Morpho
    handler: src/EventHandlers.ts
    events:
      - event: CreateMarket(bytes32 indexed id, (address,address,address,address,uint256) marketParams)
      - event: Liquidate(bytes32 indexed id, address indexed caller, address indexed borrower, uint256 repaidAssets, uint256 repaidShares, uint256 seizedAssets, uint256 badDebtAssets, uint256 badDebtShares)
        field_selection:
          transaction_fields:
            - hash
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: AaveProxy
        address:
          - 0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2